### ISSUE TITLE
Support `eol` boolean response from endoflife.date

### ISSUE THREAD

**Issue by lomky** [Coolomina/eol-rb#4]
### Issue
endoflife.date can return either a datestring _or_ a boolean for the value in `eol` for a particular cycle. Support that response as well.

See the [Rails 7](https://endoflife.date/api/rails/7.0.json) response as an example.

### To reproduce
in the console:
```ruby
irb(main):001:0> EOL.info('ruby', cycle: '2.6').supported?
=> false
irb(main):002:0> EOL.info('rails', cycle: '7.0').supported?
lib/eol_rb/models/cycle.rb:11:in `parse': no implicit conversion of false into String (TypeError)

        @eol = Date.parse(specs.fetch("eol"))
                          ^^^^^^^^^^^^^^^^^^
	from lib/eol_rb/models/cycle.rb:11:in `initialize'
	from lib/eol_rb/cycle.rb:26:in `new'
	from lib/eol_rb/cycle.rb:26:in `get'
	from lib/eol_rb.rb:43:in `info'
	from ~/.rbenv/versions/3.2.2/lib/ruby/3.2.0/forwardable.rb:240:in `info'
	from (irb):2:in `<main>'
	from bin/console:20:in `<main>'
```

**Comment by lomky** [comment]
Working on this!
